### ISSUE TITLE
REQUEST: A GPS Route

### ISSUE THREAD

**Issue by Boomatisch** [Stunn9/danny3_outlawalert#5]
Hello there,
i use your Script for a long Time now. I like it really. Is there a Way that if we get a DISCPATCH we can set automaticly a Waypoint?

EXAMPLE: https://prnt.sc/x9zapp

Love to see this

Friendly Regards
Boomatisch

**Comment by danny3tb** [comment]
> Hello there,
> i use your Script for a long Time now. I like it really. Is there a Way that if we get a DISCPATCH we can set automaticly a Waypoint?
> 
> EXAMPLE: https://prnt.sc/x9zapp
> 
> Love to see this
> 
> Friendly Regards
> Boomatisch

This is no longer updated or supported
